### ISSUE TITLE
should not have to install fake data to get default templates

### ISSUE THREAD

**Issue by balmas** [PerseusDL/JackSON#35]
I think it should not be required to install the fake data in order to get the default templates

**Comment by caesarfeta** [comment]
Default templates will be application specific.  imgcollect angular keeps them in json_ld in the application root.  https://github.com/PerseusDL/imgcollect_angular/tree/master/json_ld There's a service called tmpl which will retrieve these templates with just the name filename - .json .  https://github.com/PerseusDL/imgcollect_angular/blob/master/angular/lib/xhr/tmpl.js It can be configured to pull in JSON-LD templates from anywhere.
